# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run tests.py

# Push the results back to codecov
after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: '27438eaff39a6d9976ef4a83da8b3a5b38fd4d07' # Set in travis-ci.org dashboard
  on:
    branch: master
