coverage:
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: "include"
    patch:
      default:
        base: "auto"
        if_ci_failed: "error"
        only_pulls: true
    project:
      default:
        if_ci_failed: "error"
        only_pulls: true
        target: "auto"

ignore:
  - 'packages/app-test/containers/MyPackage'
  - 'packages/app-test/containers/MyPackage/MyPackage.py'
  - 'packages/app-test/containers/MyPackage/**/*'


flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: 'ats-test'
      carryforward: true
      carryforward_mode: "labels"

