profiling:
  critical_files_paths:
    - app/calculator.py

comment:
  show_critical_paths: true
  layout: "diff, flags, files" 

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
