profiling:
  critical_files_paths:
    - app/calculator.py

comment:
  show_critical_paths: true

beta_groups:
  - "labels"

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
