flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: "ats-test"
      carryforward: true
      carryforward_mode: "labels"

coverage:
  status:
    project: true
    patch: true

comment:
  hide_project_coverage: false
