coverage:
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: "include"
    patch:
      default:
        base: "auto"
        if_ci_failed: "error"
        only_pulls: true
    project:
      default:
        if_ci_failed: "error"
        only_pulls: true
        target: "auto"

ignore:
  - "**/*bundle"


flag_management:
  default_rules:
    carryforward: false

cli:
  plugins:
    pycoverage:
      path_to_coverage_file: '.artifacts/.coverage'
      report_type: "json"
