version: 2.1
#orbs:
#  codecov: codecov/codecov@3.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install dependencies and package
          command: |
            pip install -r requirements.txt
            pip install .
      - run:
          name: Run tests and collect coverage
          command: |
            pip install pytest-cov
            pytest --cov=awesome --cov-report=xml tests/*.py
      - run:
          name: Upload coverage
          command:
            bash <(curl -s https://codecov.io/bash)

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
