version: 2.1
orbs:
  codecov: codecov/codecov@5

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: pytest --cov app
      - run:
          name: set -u
          command: set -u
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
