pipeline:
  name: Build example-python
  identifier: Build_codecov_example_python_1782243281624
  projectIdentifier: calvin
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      pip install codecov-cli
                      codecovcli upload-process
                    envVariables:
                      CODECOV_TOKEN: <+secrets.getValue("Codecov_Upload_Token")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: codecov/example-python
        build: <+input>
