pipeline:
  name: example-python
  identifier: examplepython
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install deps
                  identifier: Install_Deps
                  spec:
                    shell: Sh
                    command: pip install -r requirements.txt
              - step:
                  type: Run
                  name: Pytest
                  identifier: Pytest
                  spec:
                    shell: Sh
                    command: pytest --cov app
              - step:
                  type: Run
                  name: Upload to Codecov
                  identifier: Codecov
                  spec:
                    shell: Sh
                    command: |
                      curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
                      curl -Os https://cli.codecov.io/latest/linux/codecov
                      curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM
                      curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM.sig
                      gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
                      shasum -a 256 -c codecov.SHA256SUM
                      chmod u+x ./codecov
                      ./codecov --verbose upload-process -t $CODECOV_TOKEN
                    envVariables:
                      CODECOV_TOKEN: <+secrets.getValue("CODECOV_TOKEN")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1778001905690
        repoName: codecov/example-python
        build: <+input>
