name: Workflow for Codecov example-python
on: 
  pull_request:
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Restore cache for pull requests
        if: github.event_name == 'pull_request'
        id: restore_cache_pull
        uses: actions/cache@v3
        with:
          path: coverage.xml
          key: coverage-${{ github.event.pull_request.head.sha }}

      - name: Run tests and collect coverage
        if: steps.restore_cache_pull.outputs.cache-hit != 'true' 
        run: pytest --cov app

      - name: Cache codecov for pull requests
        if: steps.restore_cache_pull.outputs.cache-hit != 'true' 
        uses: actions/cache@v3
        with:
          path: coverage.xml
          key: coverage-${{ github.event.pull_request.head.sha }}
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      