name: Workflow for main PRs
on: 
  pull_request:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://infra-prod-docs/soramitsu/iroha2/codecov/coverage.xml
          destination: ./coverage.xml
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1

      # - name: Restore cache for pull requests
      #   if: github.event_name == 'pull_request'
      #   id: restore_cache_pull
      #   uses: actions/cache@v3
      #   with:
      #     path: coverage.xml
      #     key: coverage-${{ github.event.pull_request.head.sha }}

      - name: Run tests and collect coverage
        if: steps.restore_cache_pull.outputs.cache-hit != 'true' 
        run: pytest --cov app

      # - name: Cache codecov for pull requests
      #   if: steps.restore_cache_pull.outputs.cache-hit != 'true' 
      #   uses: actions/cache@v3
      #   with:
      #     path: coverage.xml
      #     key: coverage-${{ github.event.pull_request.head.sha }}
      
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: coverage.xml
          destination: s3://infra-prod-docs/soramitsu/iroha2/codecov/coverage.xml
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      