name: Upload coverage to Codecov
on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
